os: Visual Studio 2015
configuration: Debug
platform: x64

environment:
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_67_0\\lib64-msvc-14.0"
  PATH: "%BOOST_LIBRARYDIR%;%PATH%"

build_script:
  - echo "Hello World"